MOV R10, #0 ; COUNTER (i)
MOV R11, #5 ; Input_Number_1
MOV R12, #10 ; Input_Number_2
MOV R13, #0 ; RESULT

FOR
	CMP R10, R11 ; COMPARE OPERATOR TO CHECK IF THEY'RE =
	BGE DONE ; IF THEY'RE EQUAL --> END

	ADD R13, R13, R12 ; COUNTING RESULT
	ADD R10, R10, #1 ; INCREMENT COUNTER
	B FOR ; ITERATE LOOP AGAIN
DONE